---
name: "release"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Bump type"
        default: "patch"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  attestations: write
  id-token: write
  contents: write

env:
  FOLDER_NAME: "MinUI"
  ZIP_NAME: "MinUI.zip"

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Create package
        run: make

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2.2.3
        with:
          subject-path: "${{ env.ZIP_NAME }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.1
        with:
          name: "${{ env.ZIP_NAME }}"
          path: "${{ env.ZIP_NAME }}"

      - name: Get Latest Tag
        id: latest-tag
        run: |
          GIT_LATEST_TAG="$(git describe --tags "$(git rev-list --tags --max-count=1 2>/dev/null || true)" 2>/dev/null || true)"
          if [[ -z "$GIT_LATEST_TAG" ]]; then
            GIT_LATEST_TAG="0.0.0"
          fi
          echo "GIT_LATEST_TAG=${GIT_LATEST_TAG}" >>"$GITHUB_OUTPUT"

      - name: Compute Next Tag
        id: next-tag
        uses: docker://ghcr.io/dokku/semver-generator:latest
        with:
          bump: ${{ github.event.inputs.bump_type }}
          input: ${{ steps.latest-tag.outputs.GIT_LATEST_TAG }}

      - name: Create and Push Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag "$GIT_NEXT_TAG"
          git push origin "$GIT_NEXT_TAG"
        env:
          GIT_NEXT_TAG: ${{ steps.next-tag.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: "${{ env.ZIP_NAME }}"
          generate_release_notes: true
          make_latest: "true"
          tag_name: ${{ steps.next-tag.outputs.version }}
